CREATE TABLE `jm_tender` (
 `id` BIGINT(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,
 `tenderTitle`           VARCHAR(50)  NOT NULL COMMENT '招标标题',
 `tenderCode`            VARCHAR(30)  NOT NULL COMMENT '招标Code',
  `status`               INT(2)       NOT NULL COMMENT '招标状态',
 `coalTypeId`            INT(2)       NOT NULL COMMENT '煤种id',
 `coalZoneId`            INT(2)       NOT NULL COMMENT '煤矿id',
 `forwardStationId`      INT(2)       NOT NULL COMMENT '发站id',
 `transportModeId`       INT(2)       NOT NULL COMMENT '运输方式id',
 `saleAmount`            INT(11)      NOT NULL COMMENT '发售量',
 `margins`               DECIMAL(9, 2) DEFAULT NULL COMMENT '保证金',
 `saleBasePrice`         DECIMAL(8, 2) NOT NULL COMMENT '竞买底价',
 `saleIncreasePriceStep` INT (3) NOT NULL COMMENT '加价幅度',
 `minimumSaleAmount`     INT(11)       NOT NULL COMMENT '最低竞买量',
 `settlementModeStr`     VARCHAR(2000) NOT NULL COMMENT '保证金支付方式说明',
 `tenderStartDate`       DATETIME      NOT NULL COMMENT '报价开始时间',
 `tenderEndDate`         DATETIME      NOT NULL COMMENT '报价开始时间',
 `projectStr`            TEXT          NOT NULL COMMENT '报价截止时间',
 `KPIStr`                VARCHAR(2000) NOT NULL COMMENT '考核文本',
 `qualificationStr`      VARCHAR(2000) NOT NULL COMMENT '资质文本',
 `marginsStr`            VARCHAR(2000) NOT  NULL COMMENT '保证金文本',
 `saleRuleStr`           VARCHAR(2000) NOT NULL COMMENT '竞买规则文本',
 `createDate`            DATETIME      DEFAULT CURRENT_TIMESTAMP  COMMENT '创建时间',
 `createBy`              VARCHAR(40)   NOT NULL COMMENT '创建人'
);